<a href="https://colab.research.google.com/github/Dharma-Ranganathan/AllAboutPython/blob/main/DA_Projects_Codes/Linear_Algebra/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is matrix -

* Combination of vectors
* Consists of rows and columns

Why we use matrix -

* Reading binaries is in matrices format only
* Csv and Excel datasheet contains rows and columns so, matrix is needed for data manipulation and extraction

How to use matrix -

* Using python libraries like numpy and pandas

Let's see further...

In [1]:
# creating a matrix in manual way

matrix_a = [[2,3,4],[5,6,7],[8,9,10]]

print(matrix_a)

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]


In above matrix, we have done it in manual with 3 x 3 matrix format

3x3 - 3 rows x 3 columns

In [2]:
# creating a matrix using numpy

import numpy as np

matrix_b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Same as before matrix, we did 3 x 3 matrix using numpy library

Now on, we are going to use numpy to make matrices and work with it

In [3]:
# create a random matrices

matrix_rand = np.random.rand(3,3)

print(matrix_rand)

[[0.83505761 0.81596768 0.4102362 ]
 [0.99425895 0.599883   0.68062824]
 [0.77134286 0.82715833 0.51270292]]


Above, np.random.rand(3,3)

* random module
* rand function
* 3,3 - shape of matrix we needed

* takes 0 - 1 values randomly and creates matrix

In [4]:
# creating matrix using randint method

matrix_int = np.random.randint(1,100,(3,3))

print(matrix_int)

[[77 71 54]
 [59 69  3]
 [19 84 17]]


Above, np.random.randint(1,100,(3,3))

* 1 - value starts from
* 100 - value ends to
* (3,3) - shape of matrix - 3x3 matrix

In [5]:
# checking shape of matrix for before one

matrix_int.shape

(3, 3)

In [7]:
# creating null matrix

matrix_null = np.zeros((3,3))

print(matrix_null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Above, np.zeros((3,3))

* zeros() function
* (3,3) - shape of matrix
* returns values in float value

In [8]:
# creating null matrix with int type

matrix_null_int = np.zeros((3,3),dtype=int)

print(matrix_null_int)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Above, np.zeros((3,3),dtype=int)

* (3,3) - shape of matrix
* dtype = int - converts values/elements in int type

In [18]:
# creating identity matrix

matrix_eye = np.eye(3,3,dtype=int)

print(matrix_eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Above, np.eye(3,3,dtype=int)

* 3,3 - shape of matrix
* dtype - int type
* eye() - method to create identity matrix - diagonally presence of 1 in matrix according to given shape

In [22]:
# checking shape and dimension of matrix_int

print(matrix_int.shape)
print(matrix_int.ndim)

(3, 3)
2


Above,
* shape - class variable - returns shape of matrix
* ndim - class variable - returns no of dimensions

In [27]:
# matrix operations - addition

A = np.random.randint(1,10,(2,2))
B = np.random.randint(1,10,(2,2))

print("A:",A)
print("B:",B)
print()

# addition - manual way

print(A+B)
print()

# addition - using numpy

C = np.add(A,B)
print(C)
print()

A: [[3 8]
 [3 1]]
B: [[3 1]
 [9 5]]

[[ 6  9]
 [12  6]]

[[ 6  9]
 [12  6]]



Above, we can do some mathematical operations in matrix

* Addition in manual way
* Addition using numpy methods - add()

* Note : when we do some operations like add, sub, mul, div - make sure to have same shape of matrix to two matrices.

* Methods we have, add(), subtract(), multiply(), divide()

In [28]:
# Subtraction

# subtraction - manual way

print(A-B)
print()

# subtraction - using numpy

D = np.subtract(A,B)
print(D)

[[ 0  7]
 [-6 -4]]

[[ 0  7]
 [-6 -4]]


In [29]:
# Multiplication

# multiplication - manual way

print(A*B)
print()

# multiplication - using numpy

E = np.multiply(A,B)
print(E)

[[ 9  8]
 [27  5]]

[[ 9  8]
 [27  5]]


In [30]:
# Division

# division - manual way

print(A/B)
print()

# division - using numpy

F = np.divide(A,B)
print(F)

[[1.         8.        ]
 [0.33333333 0.2       ]]

[[1.         8.        ]
 [0.33333333 0.2       ]]


So far, we've done some mathematical operations between two matrices, now we are gonna approach with vectors and scalar to matrix operations.

Let's try...

In [44]:
# multiplication of matrix with scalar

# simply increase the matrix

matrix_mul = np.random.randint(1,3,(2,2))

# scalar value

scal_a = 2

# before

print("matrix :",matrix_mul)
print()

print("scalar :",scal_a)
print()

# after

G = np.multiply(matrix_mul,scal_a)
print(G)

matrix : [[2 1]
 [1 2]]

scalar : 2

[[4 2]
 [2 4]]


Above ,

* Scalar - singly magnitude value without directions

* Vector - both magnitude and direction enabled values

Scalar = 45

Vector = [1,2,3] - 3 columns / 1 row
* Either 1 row / n columns
* Or n rows / 1 column

Matrix = n columns and n rows

Operations - matrix with scalar
* Returns matrix only

Operations - matrix with vector
* Returns matrix only

In [47]:
# multiplication - matrix with vector

matrix_mul_1 = np.random.randint(1,3,(2,2))

print("matrix :",matrix_mul_1)

# vector - taking n_rows / 1 column

vector = np.array([[23],[34],[45]])

# multiplication

mul = np.multiply(matrix_mul_1,vector)
print(mul)

matrix : [[2 1]
 [2 1]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,1) 

Above, when we do some operations between matrix and vectors, do before doing this,

Matrix shape - 2,2

Vector shape - 3,1

Doing operations:
Make sure you have, columns of matrix is equal to rows of vectors.

Same for between two matrices

Make sure you have, columns of one matrix is equal to rows of another matrix.

In [49]:
# after understanding rule

matrix_mul_2 = np.random.randint(1,3,(2,2))

# matrix shape

print(matrix_mul_2.shape)
print("matrix :",matrix_mul_2)
print()

# vector
vector_1 = np.array([[23],[34]])

# vector shape

print(vector_1.shape)
print("vector :",vector_1)
print()

# multiplication

H = np.multiply(matrix_mul_2,vector_1)
print(H)

(2, 2)
matrix : [[1 2]
 [1 1]]

(2, 1)
vector : [[23]
 [34]]

[[23 46]
 [34 34]]


You may notice, columns of matrix is same as rows of vectors / matrix...

Transpose of matrix:

In [50]:
# transpose of matrix
matrix = np.random.randint(1,100,(5,5))

# before
print(matrix)
print()

# after
trans_matrix = np.transpose(matrix)
print(trans_matrix)

[[45 84 98 57  1]
 [17 53 72 23 55]
 [73 40 88 87 76]
 [46 38  9 69 10]
 [ 6 84 54 21 79]]

[[45 17 73 46  6]
 [84 53 40 38 84]
 [98 72 88  9 54]
 [57 23 87 69 21]
 [ 1 55 76 10 79]]


Transpose :

Which means rows transform into columns and columns transform into rows

Last, multiplication of two matrices

As told previously, columns of one matrix is equal to rows of another matrix is needed.

In [57]:
# multiplication of two matrices

Ab = np.random.randint(1,100,(2,2))
Bc = np.random.randint(1,100,(2,2))

# before
print(Ab)
print()
print(Bc)
print()

# after - normal multiplication
X = np.multiply(Ab,Bc)
print(X)

[[18 57]
 [79 64]]

[[58 61]
 [88 25]]

[[1044 3477]
 [6952 1600]]

[[ 6060  2523]
 [10214  6419]]


On multiplying two matrices , we get element wise multiplication - returns 3rd output.

Thank you ...